interface INexoosBorrowerRequest {
    skip_invitation: string,
    borrower: {
      email: string,
      cnpj: string,
      last_year_revenue: number //1...11 *required **check allowed values
      foundation_year: string,
      address_zip_code: string,
      responsible_name: string,
      responsible_cpf: string,
      responsible_politically_exposed: boolean,
      company_name: string,
      fantasy_name: string,
      simples_nacional: boolean,
      phone_number: string,
      employees_number: number,
      small_description: string,
      company_logo: string,
      remote_company_logo_url: string,
      address_street: string,
      address_number: string,
      address_complement: string,
      address_neighborhood: string,
      address_city: string,
      address_state: string,
      address_country: string,
      company_website: string,
      economic_group_name: string,
      social_links: string, //comma,separated,strings
      responsible_occupation: string,
      birthday: string,
      responsible_civil_status: string,
      responsible_rg: 0,
      responsible_rg_issuer: string,
      state_subscription: string,
      commercial_phone: string,
      invitation_message: string,
      borrower_bank_account_attributes: {
        bank_id: string,
        agency_number: string,
        account_number: string
      },
      loan_guarantors_attributes: {
        email: string,
        name: string,
        cpf: string,
        nationality: string, //(Brasileira,Estrangeira),
        address_street: string,
        address_number: string,
        address_complement: string,
        address_neighborhood: string,
        address_zip_code: string,
        address_city: string,
        address_state: string,
        politically_exposed: boolean,
        patrimony: number,
        income: number,
        is_administrator: boolean,
        rg: string,
        rg_issuer: string,
        birth_place: string,
        civil_status: string,
        birthday: string,
        gender: string,
        profession: string,
        phone_number: string,
        percentage: number,
        is_guarantor: boolean,
        rg_issue_date: string,
        rg_issuer_uf: string,
        mother_name: string,
        father_name: string
      },
      accountant_info_attributes: {
        accountant_name: string,
        accountant_email: string,
        accountant_phone: string
      }
    }
}
