/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projeto.teste

import it.skrape.core.htmlDocument
import it.skrape.fetcher.*
import it.skrape.selects.html5.div

fun searchWordMeaning(name: String): Palavra {

    val meaning = skrape(HttpFetcher) {

        request {
            url = "https://www.dicionariodenomesproprios.com.br/$name/"
        }

        response(fun Result.(): String {
            val parsedHtml = htmlDocument {
                div("#significado>p") {
                    findFirst {
                        text
                    }
                }
            }
            return parsedHtml
        })
    }
    val palavra = Palavra(name, meaning)

    return palavra
}

fun main() {
    println(searchWordMeaning("Abraão"))
}

data class Palavra(val word: String, val meaning: String)
