/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projeto.teste

import it.skrape.core.htmlDocument
import it.skrape.fetcher.*
import it.skrape.selects.eachHref
import it.skrape.selects.eachText
import it.skrape.selects.html5.a
import it.skrape.selects.html5.p
import it.skrape.selects.html5.span
import it.skrape.selects.text

fun main() {

    val name = "amor"

    val meaning = skrape(HttpFetcher) {

        request {
            url = "https://www.dicio.com.br/$name/"
        }

        response(fun Result.(): List<String> {
            val parsedHtml = htmlDocument {
                p(".significado.textonovo>span:not(.cl):not(.etim):not(.cl-block)") {
                    findAll {
                        eachText
                    }
                }
            }

            return parsedHtml
        })
    }

    val palavra = Palavra(name, meaning)

    println(palavra)
}

data class Palavra(val word: String, val meaning: List<String>)
