/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projeto.teste

import it.skrape.core.htmlDocument
import it.skrape.fetcher.*
import it.skrape.selects.eachHref
import it.skrape.selects.eachText
import it.skrape.selects.html5.a
import it.skrape.selects.html5.p
import it.skrape.selects.html5.span
import it.skrape.selects.text

fun main() {
    val links: List<String> = skrape(HttpFetcher) {
        request {
            url = "https://www.dicio.com.br/advir/"
        }
        extract {
            htmlDocument {
                p(".significado.textonovo>span:not(.cl):not(.etim):not(.cl-block)") {
                    findAll {
                        eachText
                    }
                }
            }
        }
    }
    println(links)
}

class Palavra(var name: String, var meaning: String) {}
