export enum ContractStatusEnum {
  CREATED = 'CREATED',
  READY = 'READY', 
  ERROR = 'ERROR', 
  PENDENT = 'PENDENT',
  NOTDISTURB = 'NOTDISTURB',
  CONTACTED = 'CONTACTED',
  REFUSED = 'REFUSED',
  ACCEPTED = 'ACCEPTED'
}